ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name="cart"
urlpatterns = [
    path('addtocart/<int:i>',views.AddtoCart.as_view(),name="addtocart"),
    path('cartview',views.CartView.as_view(),name='cartview'),
    path('minus/<int:i>',views.RemoveOne.as_view(),name="minus"),
    path('remove/<int:i>',views.Remove.as_view(),name="remove"),
    path('checkout', views.Checkout.as_view(), name='checkout'),
    path('payment_success/<i>', views.Payment_success.as_view(), name='payment_success'),
    path('your_orders', views. Yourorders.as_view(), name='your_orders'),

]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name="search"
urlpatterns = [
     path('',views.Search.as_view(),name='searchitem' ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name="shop"
urlpatterns = [
    path('', views.Categories.as_view(),name='categories'),
    path('products/<int:i>', views. Products.as_view(),name='products'),
    path('productdetail/<int:i>', views. ProductDetail.as_view(),name='productdetail'),
    path('register', views.Register.as_view(), name='register'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('adminpage', views.Admin.as_view(), name='adminpage'),
    path('addcategory', views.AddCategory.as_view(), name='addcategory'),
    path('addproduct', views.AddProducts.as_view(), name='addproduct'),
    path('addstock/<int:i>', views.Stock.as_view(), name='addstock'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.db.models.fields import DateTimeField
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.product.price * self.quantity



class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    amount=models.IntegerField(null=True)
    order_id=models.CharField(max_length=30,null=True)
    phone = models.IntegerField()
    address=models.TextField()
    payment_method = models.CharField(max_length=30)
    ordered_date = models.DateTimeField(auto_now_add=True)
    is_ordered=models.BooleanField(default=False)
    delivery_status=models.CharField(default="pending")
    def __str__(self):
        return self.user.username


class Order_items(models.Model):
     product=models.ForeignKey(Product,on_delete=models.CASCADE)
     order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='products')
     quantity=models.IntegerField()
     def __str__(self):
         return self.product.name

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
from . models import Order

class OrderForm(forms.ModelForm):
    payment_choices=[('cod','COD'),('online','ONLINE')]
    payment_method=forms.ChoiceField(choices=payment_choices)
    class Meta:
        model=Order
        fields=['address','phone','payment_method']

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from cart.models import Cart
from cart.forms import OrderForm
from django.contrib import messages
from cart.models import Order

import razorpay

from cart.models import Order_items


class AddtoCart(View):
   def get(self,request,i):
       p=Product.objects.get(id=i)
       u=request.user
       try:
           c=Cart.objects.get(user=u,product=p) #checks whether the product already placed by the current user or
           c.quantity+=1                        #checks whether the product is there in the cart table
           c.save()                             #if yes increments the quantity by 1
       except:
           c=Cart.objects.create(user=u,product=p,quantity=1) # else creates a new cart record inside cart table
           c.save()
       return redirect('cart:cartview')

class CartView(View):
    def get(self,request):
        p=Product
        u=request.user
        c=Cart.objects.filter(user=u) #filters the cart items selected by current user

        total=0
        for i in c:
            total+=i.product.price*i.quantity


        context={'cart':c,'total':total}
        return render(request,'cartview.html',context)



class RemoveOne(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user #current user
        try:

            c=Cart.objects.get(user=u,product=p)
            if c.quantity>1:
              c.quantity-=1
              c.save()
            else:
                c.delete()
        except:
            pass
        return redirect('cart:cartview')


class Remove(View):
    def get(self,request,i):
        p = Product.objects.get(id=i)
        u = request.user  # current user
        try:
            c=Cart.objects.get(user=u,product=p)
            c.delete()

        except:
            pass
        return redirect('cart:cartview')



def checkstock(c):
    stock=True
    for i in c:
        if i.product.stock < i.quantity:
            stock=False
            break
    else:
        stock =True
    return stock

import uuid
class Checkout(View):


    def get(self,request):

        u = request.user
        c = Cart.objects.filter(user=u)  # filters the cart items selected by current user
        stock=checkstock(c)
        if stock:
            form_instance = OrderForm()
            context={'form':form_instance}
            return render(request,'checkout.html',context)
        else:
          messages.error(request,"Currently Items not available,can't place Order")
          return render(request,'checkout.html')



    def post(self,request):
        form_instance=OrderForm(request.POST)
        if form_instance.is_valid():
           o=form_instance.save(commit=False) #for adding additional details set commit is false
           u=request.user #current user
           o.user=u
           c=Cart.objects.filter(user=u)
           total=0
           for i in c:
               total+=i.product.price*i.quantity
           o.amount=total
           o.save()
           if(o.payment_method=="online"):
               #Razorpay client connection
              client=razorpay.Client(auth=('rzp_test_RdJOGsBHZubILn','Dnp6hJH00QvXttr114xFssvD'))
              print(client)
              #place order
              response_payment = client.order.create(dict(amount=total*100,currency='INR'))
              print(response_payment)
              id=response_payment['id']
              o.order_id=id
              o.save()
              context={'payment':response_payment}
           else:
              o.is_ordered=True
              uid=uuid.uuid4().hex[:14]
              id='order_COD'+uid # manaually creates orderid for COD orders using uuid module
              o.order_id=id
              o.save()


              c = Cart.objects.filter(user=u)
              for i in c:
                  items = Order_items.objects.create(order=o, product=i.product, quantity=i.quantity)
                  items.save()
                  items.product.stock -= items.quantity
                  items.product.save()

                  # cart deletion
                  c.delete()

        return render(request,'payment.html')

from django.contrib.auth.models import User
from django.contrib.auth import login
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
@method_decorator(csrf_exempt,name="dispatch")
class Payment_success(View):
    def post(self,request,i): # here i represent to the username
                                    #to add the user to the current session again
        u=User.objects.get(username=i)
        login(request,u) #adds the user object u into session
        response=request.POST
        print(response) #after payment razorpay sends payment details into success view
                        #as response
        id=response['razorpay_order_id']
        print(id)

        #order
        order=Order.objects.get(order_id=id)
        order.is_ordered=True #after  succesful completion of order
        order.save()


        #order_items
        c=Cart.objects.filter(user=u)
        for i in c:
            o=Order_items.objects.create(order=order,product=i.product,quantity=i.quantity)
            o.save()
            o.product.stock-=o.quantity
            o.product.save()

        #cart deletion
            c.delete()


        return render(request,'payment_success.html')



class Yourorders(View):
       def get(self,request):
           u=request.user
           order=Order.objects.filter(user=u,is_ordered=True)
           context={'orders':order}
           return render(request,'your_orders.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from django.views import View
from shop.models import Product
from django.db.models import Q
# Create your views here.
class Search(View):
  def get(self,request):
    query = request.GET['q']
    #print(query)
    if query:
        p = Product.objects.filter(Q(name__icontains=query) | Q(price__icontains=query))
        context = {'items': p}
    return render(request, 'search.html', context)

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center">Add Category</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container border border-3 border-secondary p-5 mt-5 text-center">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {{form|crispy}}
     <input type="submit">
    </form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center">Add Stock</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container border border-3 border-secondary p-5 mt-5 text-center">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {{stock|crispy}}
     <input type="submit">
    </form>
</div>
{% endblock %}

ecommerce/templates/adminpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Cart View</h2>
 <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->
{{cart}}
    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th> Unit Price</th>
                                    <th>Quantity</th>
                                    <th>Subtotal</th>
                                    <th>actions</th>
                                </tr>
                            </thead>
                            <tbody>
                           {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{i.product.image.url}}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box"><p>{{i.quantity}}</p></td>
                                    <td class="total-pr">
                                        <p>{{i.subtotal}}</p>
                                    </td>
                                    <td class="remove-pr">

                                     {% if i.product.stock > 0 %}

                                        <a href="{% url 'cart:addtocart' i.product.id %}">
									<i class="fa-solid fa-plus" ></i>
								</a>

                                        <a href="{% url 'cart:minus' i.product.id %}">
									<i class="fa-solid fa-minus"></i>
								</a>
                                          <a href="{% url 'cart:remove' i.product.id %}">
									<i class="fas fa-times  "></i>
								</a>

                                    {% else %}
                                         <a href="{% url 'cart:minus' i.product.id %}">
									<i class="fa-solid fa-minus"></i>
								</a>
                                          <a href="{% url 'cart:remove' i.product.id %}">
									<i class="fas fa-times  "></i>
								</a>
                                        {% endif %}
                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Total</h4>
                            <div class="ml-auto font-weight-bold">{{total}}</div>
                        </div>

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5">{{total}}</div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->
{% endblock %}

ecommerce/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="border border-secondary 2px solid ">
 <h2 class="text-center">CATEGORIES</h2>

   <!-- Start Slider -->
<div id="slides-shop" class="cover-slides">
    <ul class="slides-container">
        {% for i in category %}
        <li class="text-center">
            <img src="{{ i.image.url }}" alt="">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                        <p class="m-b-40">
                            See how your users experience your website in realtime or view
                            trends to see any changes in performance over time.
                        </p>
                        <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="slides-navigation">
        <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    </div>
</div>

     <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>Our Collections</h1>
                        <p class="text-align:justify;line-height:2.5, font-size:20px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    </div>
                </div>
            </div>
   <!-- Start Categories  -->
    <div class="categories-shop">
        <div class="container">
            <div class="row">
              {% for i in category %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img  src="{{ i.image.url }}" alt="" style="height: 250px; width: 150%;"/>
                        <a class="btn hvr-hover" href="{% url 'shop:products'  i.id %}">{{i.name}}</a>
                    </div>
                </div>
             {% endfor %}
                </div>
        </div>
    </div>
        </div> </div> </div>
{% endblock %}

ecommerce/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Page Title -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Checkout</h2>
                <ul class="breadcrumb justify-content-center">
                    <li class="breadcrumb-item"><a href="#">Shop</a></li>
                    <li class="breadcrumb-item active">Checkout</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->

<!-- Start Checkout Section -->
<div class="container my-5">
    <div class="row justify-content-center">
        <!-- Billing Address Card -->
        <div class="col-md-8 col-lg-6">
            <div class="card border-0 rounded-3">
                <div class="card-body p-4">
                    <h3 class="text-center mb-4">Billing Address</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{form|crispy }}
                        <div class="text-center mt-3">
                            <button type="submit" class="btn btn-primary px-4 py-2 rounded-pill">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container my-5">

    {% if messages %}
    <div class="alert alert-warning text-center" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}


    <!-- Order Summary Section -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-8 col-lg-6">
            <div class="card border-0 rounded-3">
                <div class="card-body p-4">
                    <h3 class="text-center mb-3">Your Order</h3>
                    <div class="d-flex justify-content-between">
                        <strong>Product</strong>
                        <strong>Total</strong>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>Total</span>
                        <span>{{total}}</span>
                    </div>

                    <div class="d-flex justify-content-between">
                        <span>Shipping Cost</span>
                        <span>Free</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between align-items-center">
                        <h5>Grand Total</h5>
                        <h5 class="text-success">{{total}}</h5>
                    </div>
                    <div class="text-center mt-4">
                        <a href="checkout.html" class="btn btn-success w-100 rounded-pill py-2">Place Order</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h2>DETAIL PAGE</h2>
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Login</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container border border-3 border-secondary p-5 mt-5 text-center">
<form method="post">
    {% csrf_token %}
     {{form|crispy}}
     <input type="submit">
    </form>
</div>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<div class="container mt-3 p-5 text-center w-50 ">
    {% if payment %}
<form action="{% url 'cart:payment_success' user.username %} " method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_RdJOGsBHZubILn"
    data-amount="{{payment.amount}}"
    data-currency="INR"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{user.username}}"
    data-prefill.phone="{{payment.phone}}"
    data-theme.color="green"

></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    {% else %}
    <h1>Your order placed Successfully</h1>
    {% endif %}
</div>
{% endblock content %}

ecommerce/templates/payment_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<h2>Your Order is placed Successfully</h2>

{% endblock content %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">
     <img src="{{ category.image.url }}" alt="{{ category.name }}" class="img-fluid" style="max-height:400px; width:100%;">
        <h3>{{category.name}}</h3>
        <p>{{category.description}}</p>

    </div>
<div class="container">

    <!-- Product List -->
    <div class="row special-list">
        {% for j in category.products.all %}
        <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                           <img src="{{ j.image.url }}" class="img-fluid" style="height:200px; width:100%; object-fit:cover;" alt="Image">

                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' j.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{ j.name }}</h4>
                            <h5> {{ j.price }}</h5>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

ecommerce/templates/productdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-align:justify">Detail Page</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->


    <!-- End All Title Box -->

    <!-- Start About Page  -->
    <div class="about-box-main">
        <div class="container">
            <div class="row">
				<div class="col-lg-6">
                    <div class="banner-frame"> <img class="img-fluid" src="{{product.image.url}}"  />
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="noo-sh-title-top">{{product.name}}</h2>
                    <h4>Price:Rs{{product.price}}</h4>
                    <h4>{% if product.stock > 0 %}currently {{product.stock}}items availabe{% endif %}</h4>
                    <p>{{product.description}}</p>


                    {% if user.is_superuser == True %}
                        <a class="btn hvr-hover" href="{% url 'shop:addstock' product.id %}">Add Stock</a>
                    {% else %}
                        {% if product.stock > 0 %}
					          <a class="btn hvr-hover" href="{% url 'cart:addtocart' product.id %}">Add to Cart</a>
                        {% else %}
                             <h3> Out of Stock</h3>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
                    </div>
                </div>

            </div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<h2>DETAIL PAGE</h2>
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Register</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container border border-3 border-secondary p-5 mt-5 text-center">
<form method="post">
    {% csrf_token %}
     {{form|crispy}}
     <input type="submit">
    </form>
</div>
{% endblock %}